import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// /blog is a real static file (public/blog/index.html, generated by
// scripts/build-blog-index.js), not a React route. Vite's SPA fallback would
// otherwise swallow the bare /blog and /blog/ forms and serve the app shell,
// so resolve them to the file the way nginx does in production.
const serveBlogIndex = () => {
  const rewrite = (req, _res, next) => {
    const [pathname] = (req.url || '').split('?')
    if (pathname === '/blog' || pathname === '/blog/') {
      req.url = '/blog/index.html'
    }
    next()
  }
  // Block bodies on purpose: a value returned from configureServer is treated
  // by Vite as a post-hook to invoke, and middlewares.use() returns the app.
  return {
    name: 'serve-blog-index',
    configureServer(server) {
      server.middlewares.use(rewrite)
    },
    configurePreviewServer(server) {
      server.middlewares.use(rewrite)
    },
  }
}

export default defineConfig({
  plugins: [react(), tailwindcss(), serveBlogIndex()],
  server: {
    proxy: {
      '/api/chat': {
        target: process.env.DATA_ROOM_CHAT_URL
          ? new URL(process.env.DATA_ROOM_CHAT_URL).origin
          : 'https://dataroom.moi.technology',
        changeOrigin: true,
      },
      '/api/community-calls': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
    },
  },
})
