import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

const DATA_ROOM_DEFAULT = 'https://dataroom.moi.technology'

// Never throw out of the config: this module is evaluated by `vite build`
// too, so a malformed DATA_ROOM_CHAT_URL would fail the production build
// over a value only the dev proxy ever reads.
function dataRoomOrigin() {
  const raw = process.env.DATA_ROOM_CHAT_URL?.trim()
  if (!raw) return DATA_ROOM_DEFAULT

  const candidate = /^[a-z][a-z0-9+.-]*:\/\//i.test(raw) ? raw : `https://${raw}`
  try {
    return new URL(candidate).origin
  } catch {
    console.warn(`[vite] ignoring malformed DATA_ROOM_CHAT_URL (${raw}), using ${DATA_ROOM_DEFAULT}`)
    return DATA_ROOM_DEFAULT
  }
}

// /blog is a real static file (public/blog/index.html, generated by
// scripts/build-blog-index.js), not a React route. Vite's SPA fallback would
// otherwise swallow the bare /blog and /blog/ forms and serve the app shell,
// so resolve them to the file the way nginx does in production.
const serveBlogIndex = () => {
  const rewrite = (req, _res, next) => {
    const [pathname] = (req.url || '').split('?')
    if (pathname === '/blog' || pathname === '/blog/') {
      req.url = '/blog/index.html'
    }
    next()
  }
  // Block bodies on purpose: a value returned from configureServer is treated
  // by Vite as a post-hook to invoke, and middlewares.use() returns the app.
  return {
    name: 'serve-blog-index',
    configureServer(server) {
      server.middlewares.use(rewrite)
    },
    configurePreviewServer(server) {
      server.middlewares.use(rewrite)
    },
  }
}

export default defineConfig({
  plugins: [react(), tailwindcss(), serveBlogIndex()],
  server: {
    proxy: {
      '/api/chat': {
        target: dataRoomOrigin(),
        changeOrigin: true,
      },
      '/api/community-calls': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
    },
  },
})
